
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: myPassword
  host: localhost
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bank_api_development

test:
  <<: *default
  database: bank_api_test

production:
  <<: *default
  database: bank_api_production
  username: bank_api
  password: <%= ENV["BANK_API_DATABASE_PASSWORD"] %>
